name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.23.x
          - 1.24.x
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build and Test
        run: |
          go build
          go test -race ./...
